services:
  - type: web
    name: netwatch-pro-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:asgi_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false          # se configura manualmente en el dashboard de Render
      - key: JWT_SECRET
        sync: false          # se configura manualmente en el dashboard de Render
      - key: PYTHON_VERSION
        value: 3.11.0
